#pragma once

#include "driver/gpio.h"

#define BOARD_CAMERA_POWER GPIO_NUM_0
#define BOARD_CAMERA_XCLK GPIO_NUM_4
#define BOARD_CAMERA_PCLK GPIO_NUM_7
#define BOARD_CAMERA_VSYNC GPIO_NUM_1
#define BOARD_CAMERA_HREF GPIO_NUM_2
#define BOARD_CAMERA_D0 GPIO_NUM_9
#define BOARD_CAMERA_D1 GPIO_NUM_11
#define BOARD_CAMERA_D2 GPIO_NUM_12
#define BOARD_CAMERA_D3 GPIO_NUM_10
#define BOARD_CAMERA_D4 GPIO_NUM_8
#define BOARD_CAMERA_D5 GPIO_NUM_6
#define BOARD_CAMERA_D6 GPIO_NUM_5
#define BOARD_CAMERA_D7 GPIO_NUM_3
#define BOARD_CAMERA_SDA GPIO_NUM_17
#define BOARD_CAMERA_SCL GPIO_NUM_18

#define BOARD_EPD_BUSY GPIO_NUM_38
#define BOARD_EPD_RST GPIO_NUM_45
#define BOARD_EPD_DC GPIO_NUM_39
#define BOARD_EPD_CS GPIO_NUM_40
#define BOARD_EPD_SCLK GPIO_NUM_41
#define BOARD_EPD_MOSI GPIO_NUM_42
