#pragma once

#define APP_STORAGE_MOUNT_POINT "/sdcard"
#define APP_IMAGE_DIRECTORY APP_STORAGE_MOUNT_POINT "/images"
#define APP_MAX_IMAGES 128

#define APP_AUDIO_SAMPLE_RATE_HZ 16000
#define APP_AUDIO_CAPTURE_CHANNELS 2
#define APP_AUDIO_CHANNELS 2

#define APP_COMMAND_PREVIOUS_ID 1
#define APP_COMMAND_NEXT_ID 2
#define APP_COMMAND_PREVIOUS_PHRASE "show previous picture"
#define APP_COMMAND_NEXT_PHRASE "show next picture"
#define APP_COMMAND_TIMEOUT_MS 6000
#define APP_COMMAND_DEBOUNCE_MS 1200
#define APP_WAKE_WORD "Hi ESP"
#define APP_WAKE_COMMAND_WINDOW_MS 8000

#define APP_VAD_TRAILING_AUDIO_MS 768
#define APP_VAD_MIN_SPEECH_MS 128
#define APP_VAD_MIN_NOISE_MS 450
#define APP_VAD_DELAY_MS 192
