#pragma once

#include "driver/gpio.h"

#define BOARD_SD_CLK GPIO_NUM_14
#define BOARD_SD_CMD GPIO_NUM_13
#define BOARD_SD_D0 GPIO_NUM_15

#define BOARD_EPD_BUSY GPIO_NUM_38
#define BOARD_EPD_RST GPIO_NUM_45
#define BOARD_EPD_DC GPIO_NUM_39
#define BOARD_EPD_CS GPIO_NUM_40
#define BOARD_EPD_SCLK GPIO_NUM_41
#define BOARD_EPD_MOSI GPIO_NUM_42

#define BOARD_I2C_SDA GPIO_NUM_17
#define BOARD_I2C_SCL GPIO_NUM_18
#define BOARD_I2S_MCLK GPIO_NUM_16
#define BOARD_I2S_BCLK GPIO_NUM_46
#define BOARD_I2S_LRCK GPIO_NUM_47
#define BOARD_I2S_DIN GPIO_NUM_48
#define BOARD_I2S_DIN_MIC34 GPIO_NUM_21
